version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  redis:
    driver: local

services:
  php:
    container_name: bot_php
    build: ./php
    volumes:
      - ${WORKER_DIR}:/var/www/app
    ports:
      - 9501:9501
    depends_on:
      - redis
    networks:
      - backend
  redis:
    container_name: bot_redis
    build: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
    #entrypoint: redis-server --appendonly yes --requirepass hangqun
    ports:
      - 6379:6379
    networks:
      - backend